CREATE TABLE brain_tool_definitions (
    id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    brain_id              UUID         NOT NULL REFERENCES brains (id) ON DELETE RESTRICT,
    name                  VARCHAR(120) NOT NULL,
    description           VARCHAR(1000) NOT NULL,
    mode                  VARCHAR(40)  NOT NULL,
    confirmation_required BOOLEAN      NOT NULL DEFAULT FALSE,
    required_permissions  JSONB        NOT NULL DEFAULT '[]'::jsonb,
    input_schema          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    is_active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            VARCHAR(100) NOT NULL,
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by            VARCHAR(100) NOT NULL,
    CONSTRAINT uq_brain_tool_definitions_brain_name UNIQUE (brain_id, name),
    CONSTRAINT chk_brain_tool_definitions_mode CHECK (mode IN ('READ', 'WRITE', 'NAVIGATE'))
);

CREATE INDEX idx_tool_definitions_brain_active
    ON brain_tool_definitions (brain_id, is_active);
CREATE INDEX idx_tool_definitions_brain_created
    ON brain_tool_definitions (brain_id, created_at DESC, id DESC);

INSERT INTO brain_tool_definitions (
    brain_id, name, description, mode, confirmation_required,
    required_permissions, input_schema, created_by, updated_by
) VALUES
('00000000-0000-0000-0000-000000000001', 'searchLoans',
 'Search dashboard loans visible to the current user.', 'READ', false,
 '["dashboard.loans.read"]'::jsonb,
 '{"type":"object","properties":{"query":{"type":"string"},"limit":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'getLoanSummary',
 'Read a summary for one loan visible to the current user.', 'READ', false,
 '["dashboard.loans.read"]'::jsonb,
 '{"type":"object","properties":{"loanId":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'listOpenTasks',
 'List open dashboard tasks visible to the current user.', 'READ', false,
 '["dashboard.tasks.read"]'::jsonb,
 '{"type":"object","properties":{"assigneeId":{"type":"string"},"dueBefore":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'getCalendarEvents',
 'Read calendar events visible to the current user.', 'READ', false,
 '["dashboard.calendar.read"]'::jsonb,
 '{"type":"object","properties":{"from":{"type":"string"},"to":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'getDocumentChecklist',
 'Read document checklist status for a visible file.', 'READ', false,
 '["dashboard.documents.read"]'::jsonb,
 '{"type":"object","properties":{"loanId":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'getIntegrationStatus',
 'Read dashboard integration health visible to the current user.', 'READ', false,
 '["dashboard.integrations.read"]'::jsonb,
 '{"type":"object","properties":{"integrationName":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'createTask',
 'Create a dashboard task after user confirmation.', 'WRITE', true,
 '["dashboard.tasks.write"]'::jsonb,
 '{"type":"object","properties":{"title":{"type":"string"},"assigneeId":{"type":"string"},"dueDate":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'updateTaskStatus',
 'Update a task status after user confirmation.', 'WRITE', true,
 '["dashboard.tasks.write"]'::jsonb,
 '{"type":"object","properties":{"taskId":{"type":"string"},"status":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'addLoanNote',
 'Add a note to a visible loan after user confirmation.', 'WRITE', true,
 '["dashboard.loans.write"]'::jsonb,
 '{"type":"object","properties":{"loanId":{"type":"string"},"note":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'scheduleFollowUp',
 'Schedule a follow-up after user confirmation.', 'WRITE', true,
 '["dashboard.calendar.write"]'::jsonb,
 '{"type":"object","properties":{"subject":{"type":"string"},"dateTime":{"type":"string"},"attendeeId":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'markDocumentReviewed',
 'Mark a document reviewed after user confirmation.', 'WRITE', true,
 '["dashboard.documents.write"]'::jsonb,
 '{"type":"object","properties":{"documentId":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'sendInternalMessage',
 'Send an internal dashboard message after user confirmation.', 'WRITE', true,
 '["dashboard.messages.write"]'::jsonb,
 '{"type":"object","properties":{"recipientId":{"type":"string"},"message":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18'),
('00000000-0000-0000-0000-000000000001', 'navigateToRoute',
 'Return a site-contained route.', 'NAVIGATE', false,
 '["dashboard.navigation.use"]'::jsonb,
 '{"type":"object","properties":{"route":{"type":"string"}}}'::jsonb,
 'migration-v18', 'migration-v18')
ON CONFLICT (brain_id, name) DO NOTHING;
