-- V4 — parsed content: pages, text spans, layout elements, parser output.
-- Column definitions: docs/DATA_MODEL.md section 4. Every box stored here is
-- CANONICAL: PDF points, top-left origin, rotation-0, 0.1pt rounding — the
-- worker's geometry module is the single conversion point and the Java side
-- stores values verbatim (docs/WORKER_CONTRACT.md invariant 1).
-- Every table is tenant-isolated (org_id + FORCE RLS) — RlsCoverageIT enforces
-- this structurally.

-- One rendered/parsed page of a source file.
--
-- package_id is denormalized from source_file DELIBERATELY: without it, the
-- uniqueness of package_page_index across a package cannot be expressed as a
-- database constraint — only as application logic, which is exactly the kind
-- of ordering invariant that silently breaks under concurrent ingestion of
-- multi-file packages (docs/DATA_MODEL.md 4).
--
-- text_layer defaults to 'NONE' at render time; the TEXT_EXTRACTION stage
-- overwrites it with the worker's per-page verdict. uncovered_regions holds
-- the /v1/text uncoveredRegions boxes for MIXED pages (canonical space) so the
-- OCR stage can restrict OCR to them without re-reading the raw parser_output
-- payload from blob storage.
CREATE TABLE page (
    id                     uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id                 uuid          NOT NULL REFERENCES tenant (id),
    source_file_id         uuid          NOT NULL REFERENCES source_file (id),
    package_id             uuid          NOT NULL REFERENCES document_package (id),
    -- 0-based within the source file.
    page_index             int           NOT NULL,
    -- 0-based across the whole package — the stable review ordering.
    package_page_index     int           NOT NULL,
    -- Rotation-0 dimensions, PDF points.
    width_pt               numeric(10,2) NOT NULL,
    height_pt              numeric(10,2) NOT NULL,
    -- Declared /Rotate in the PDF: 0/90/180/270.
    rotation               int           NOT NULL DEFAULT 0,
    -- From Tesseract OSD during OCR.
    detected_rotation      int,
    osd_confidence         numeric(5,4),
    text_layer             text          NOT NULL DEFAULT 'NONE',
    is_blank               boolean       NOT NULL DEFAULT false,
    blank_score            numeric(5,4),
    -- Normalized content hash — duplicate-page detection.
    content_hash           char(64),
    -- Page image blob (PNG from /v1/render).
    render_storage_key     text,
    render_dpi             int,
    -- Winning engine at page level; 'NONE' when every gate tripped on both.
    ocr_engine             text,
    -- Which gate tripped (G1_COVERAGE … G6_GEOMETRY), or OCR_LOW_CONFIDENCE
    -- when both engines failed every gate — the flag review reads.
    ocr_fallback_reason    text,
    ocr_confidence_median  numeric(5,4),
    extraction_confidence  numeric(5,4),
    -- /v1/text uncoveredRegions for MIXED pages: [{x, y, width, height}] in
    -- canonical space. NULL for NATIVE/SCANNED/NONE.
    uncovered_regions      jsonb,
    created_at             timestamptz   NOT NULL DEFAULT now(),
    updated_at             timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT page_text_layer_check
        CHECK (text_layer IN ('NATIVE', 'SCANNED', 'MIXED', 'NONE')),
    CONSTRAINT page_rotation_check CHECK (rotation IN (0, 90, 180, 270)),
    CONSTRAINT page_source_page_key UNIQUE (source_file_id, page_index),
    CONSTRAINT page_package_page_key UNIQUE (package_id, package_page_index)
);

CREATE INDEX page_org_content_hash_idx ON page (org_id, content_hash);
CREATE INDEX page_org_package_order_idx ON page (org_id, package_id, package_page_index);

-- The atomic unit of traceable text. THE volume table (~30k–70k rows per
-- 75-page package), which is why the key is a bigint identity rather than the
-- uuid every other tenant table uses: half the key width, sequential inserts,
-- and nothing external ever addresses a span by id alone. The entity therefore
-- does NOT extend TenantScopedEntity (UUID id, updated_at) — it is a slim
-- append-only entity with its own @TenantId org_id; rows are never updated,
-- so no updated_at.
CREATE TABLE text_span (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      uuid          NOT NULL REFERENCES tenant (id),
    page_id     uuid          NOT NULL REFERENCES page (id),
    -- Reading order within the page.
    ordinal     int           NOT NULL,
    text        text          NOT NULL,
    -- Canonical space, verbatim from the worker (0.1pt).
    x           numeric(10,2) NOT NULL,
    y           numeric(10,2) NOT NULL,
    width       numeric(10,2) NOT NULL,
    height      numeric(10,2) NOT NULL,
    source      text          NOT NULL,
    -- RAPIDOCR · TESSERACT. Per SPAN, not per page: reconciliation may mix
    -- engines by region and evidence must name the engine that produced it.
    ocr_engine  text,
    -- Per-word from OCR; 1.0 for native.
    confidence  numeric(5,4)  NOT NULL,
    font_size   numeric(6,2),
    font_name   text,
    created_at  timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT text_span_source_check CHECK (source IN ('NATIVE', 'OCR'))
);

CREATE INDEX text_span_page_ordinal_idx ON text_span (page_id, ordinal);
CREATE INDEX text_span_org_page_idx ON text_span (org_id, page_id);

-- Layout structure (Phase 3 fills these; schema lands with the rest of the
-- parsed-content DDL so Phase 3 ships code, not migrations). No JPA entities
-- exist for either table yet — deliberately: mapping them now would guess at
-- the Phase 3 detector output shape.
CREATE TABLE layout_element (
    id                 uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id             uuid          NOT NULL REFERENCES tenant (id),
    page_id            uuid          NOT NULL REFERENCES page (id),
    -- table → row → cell nesting.
    parent_element_id  uuid          REFERENCES layout_element (id),
    element_type       text          NOT NULL,
    ordinal            int           NOT NULL,
    x                  numeric(10,2) NOT NULL,
    y                  numeric(10,2) NOT NULL,
    width              numeric(10,2) NOT NULL,
    height             numeric(10,2) NOT NULL,
    -- Denormalized convenience.
    text               text,
    confidence         numeric(5,4)  NOT NULL,
    detector           text          NOT NULL,
    detector_version   text          NOT NULL,
    attributes         jsonb,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT layout_element_type_check CHECK (element_type IN (
        'PARAGRAPH', 'HEADER', 'TABLE', 'TABLE_ROW', 'TABLE_CELL',
        'FORM_FIELD', 'CHECKBOX', 'SIGNATURE', 'IMAGE', 'LINE'))
);

CREATE INDEX layout_element_org_page_idx ON layout_element (org_id, page_id, ordinal);

-- Join table rather than a span range so regrouping stays possible.
-- org_id is NOT in DATA_MODEL's minimal column list but is required here:
-- every table must carry org_id + FORCE RLS (RlsCoverageIT enforces it
-- structurally), and a join table is still tenant data.
CREATE TABLE layout_element_span (
    layout_element_id  uuid    NOT NULL REFERENCES layout_element (id),
    text_span_id       bigint  NOT NULL REFERENCES text_span (id),
    org_id             uuid    NOT NULL REFERENCES tenant (id),
    ordinal            int     NOT NULL,
    PRIMARY KEY (layout_element_id, text_span_id)
);

-- Immutable raw stage output. Payloads are large, so they live in blob storage
-- with only the digest in the row. BOTH OCR engines' raw outputs persist here
-- when fallback runs, regardless of which won reconciliation.
-- Rows are append-only and never updated; updated_at exists only because
-- TenantScopedEntity maps it on every tenant entity (same trade V2 documents
-- for source_file — carrying the column beats a read-only remapping hack).
CREATE TABLE parser_output (
    id                   uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id               uuid        NOT NULL REFERENCES tenant (id),
    source_file_id       uuid        REFERENCES source_file (id),
    page_id              uuid        REFERENCES page (id),
    stage                text        NOT NULL,
    parser_name          text        NOT NULL,
    parser_version       text        NOT NULL,
    payload_storage_key  text        NOT NULL,
    payload_sha256       char(64)    NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX parser_output_org_source_idx ON parser_output (org_id, source_file_id);
CREATE INDEX parser_output_org_page_idx ON parser_output (org_id, page_id);

-- ── RLS ─────────────────────────────────────────────────────────────────────
ALTER TABLE page                ENABLE ROW LEVEL SECURITY;
ALTER TABLE page                FORCE  ROW LEVEL SECURITY;
ALTER TABLE text_span           ENABLE ROW LEVEL SECURITY;
ALTER TABLE text_span           FORCE  ROW LEVEL SECURITY;
ALTER TABLE layout_element      ENABLE ROW LEVEL SECURITY;
ALTER TABLE layout_element      FORCE  ROW LEVEL SECURITY;
ALTER TABLE layout_element_span ENABLE ROW LEVEL SECURITY;
ALTER TABLE layout_element_span FORCE  ROW LEVEL SECURITY;
ALTER TABLE parser_output       ENABLE ROW LEVEL SECURITY;
ALTER TABLE parser_output       FORCE  ROW LEVEL SECURITY;

CREATE POLICY page_isolation ON page
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());
CREATE POLICY text_span_isolation ON text_span
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());
CREATE POLICY layout_element_isolation ON layout_element
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());
CREATE POLICY layout_element_span_isolation ON layout_element_span
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());
CREATE POLICY parser_output_isolation ON parser_output
    USING (org_id = current_org()) WITH CHECK (org_id = current_org());
